spring:
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config-server
    application:
        name: gallery-service
#    data:
#        mongodb:
#            uri: mongodb://localhost:27017/gallerydb

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true
