spring:
  profiles:
    active: native
---
  spring:
    profiles: native
    cloud:
      config:
        server:
          native:
            search-locations:
#              /home/ks/IdeaProjects/Gallery-Service/ms-config-properties/{application}/{profile},
              file://${user:home}/Projects/Learning/SpringBootClouds/NetflixSample/se-spring-cloud_gallery-service_ms-config
#
#  spring:
#    profiles: git
#    cloud:
#      config:
#        server:
#          git:
#            uri: https://github.com/EvadS/se-spring-cloud_gallery-service_config/
#            search-paths:
#              - "ms-config-properties/{application}/{profile}"

  eureka:
  client:
  serviceUrl:
  defaultZone: http://localhost:8761/eureka/